services:
  userbot:
    hostname: userbot
    volumes:
      - ./:/root/userbot
    image: ghcr.io/athphane/userbot


  userbot-mongo:
    hostname: userbot-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: userbot
      MONGO_INITDB_ROOT_PASSWORD: userbot-password